export const freeProContent = {
  free: {
    titleKey: "freePro.free.title",
    descriptionKey: "freePro.free.description",
    items: [
      "freePro.free.items.universal",
      "freePro.free.items.algorithms",
      "freePro.free.items.frecency",
      "freePro.free.items.calculator",
      "freePro.free.items.appShortcutSyntax",
      "freePro.free.items.highlight",
      "freePro.free.items.entryPoints",
      "freePro.free.items.quickSettings",
      "freePro.free.items.assistantRole",
      "freePro.free.items.searchBarPosition",
      "freePro.free.items.layout",
      "freePro.free.items.gridColumns",
      "freePro.free.items.iconSize",
      "freePro.free.items.gridSpacing",
      "freePro.free.items.iconLabels",
      "freePro.free.items.sectionHeaderIcons",
      "freePro.free.items.autofocus",
      "freePro.free.items.clearOnSelect",
      "freePro.free.items.hideRecentsEmpty",
      "freePro.free.items.sectionVisibilityDefault",
      "freePro.free.items.resultLimits",
      "freePro.free.items.showHideTypes",
      "freePro.free.items.hideApps",
      "freePro.free.items.hideContacts",
      "freePro.free.items.hideActions",
      "freePro.free.items.excludeFiles",
      "freePro.free.items.fileTypes",
      "freePro.free.items.freeThemes",
      "freePro.free.items.modes",
      "freePro.free.items.providersPreset",
      "freePro.free.items.providersToggle",
      "freePro.free.items.providersAlwaysShow",
      "freePro.free.items.customSection",
      "freePro.free.items.customAiPrompt",
      "freePro.free.items.privacy",
      "freePro.free.items.languages",
      "freePro.free.items.sponsored",
    ],
  },
  pro: {
    titleKey: "freePro.pro.title",
    descriptionKey: "freePro.pro.description",
    badgeKey: "freePro.pro.badge",
    priceNoteKey: "freePro.pro.priceNote",
    items: [
      "freePro.pro.items.premiumThemes",
      "freePro.pro.items.themeCreator",
      "freePro.pro.items.presets",
      "freePro.pro.items.perSectionStyle",
      "freePro.pro.items.advancedColors",
      "freePro.pro.items.searchbarColors",
      "freePro.pro.items.sectionColors",
      "freePro.pro.items.itemIconColors",
      "freePro.pro.items.bottomSheetColors",
      "freePro.pro.items.widgetColors",
      "freePro.pro.items.wallpaperBlur",
      "freePro.pro.items.advancedAnimations",
      "freePro.pro.items.sectionAnimations",
      "freePro.pro.items.sectionResize",
      "freePro.pro.items.loadOrder",
      "freePro.pro.items.animationSpeed",
      "freePro.pro.items.geometrySearchbar",
      "freePro.pro.items.searchbarLeadingIcon",
      "freePro.pro.items.hidePlaceholder",
      "freePro.pro.items.geometrySections",
      "freePro.pro.items.geometryWidget",
      "freePro.pro.items.widgetLeadingIcon",
      "freePro.pro.items.unlimitedSections",
      "freePro.pro.items.dragDropSections",
      "freePro.pro.items.reorderItems",
      "freePro.pro.items.sectionIconColors",
      "freePro.pro.items.pinnedItems",
      "freePro.pro.items.iconPacks",
      "freePro.pro.items.customProviders",
      "freePro.pro.items.providersReorder",
      "freePro.pro.items.aiPrompts",
      "freePro.pro.items.aiManage",
      "freePro.pro.items.aiReorder",
      "freePro.pro.items.backupExport",
      "freePro.pro.items.backupImport",
      "freePro.pro.items.removeAds",
      "freePro.pro.items.support",
    ],
  },
  summary: {
    titleKey: "freePro.summary.title",
    rows: [
      {
        labelKey: "freePro.summary.rows.customization",
        freeKey: "freePro.summary.values.basic",
        proKey: "freePro.summary.values.unlimited",
      },
      {
        labelKey: "freePro.summary.rows.sections",
        freeKey: "freePro.summary.values.limited",
        proKey: "freePro.summary.values.unlimited",
      },
      {
        labelKey: "freePro.summary.rows.backup",
        freeKey: "freePro.summary.values.none",
        proKey: "freePro.summary.values.included",
      },
      {
        labelKey: "freePro.summary.rows.ads",
        freeKey: "freePro.summary.values.sponsored",
        proKey: "freePro.summary.values.none",
      },
    ],
  },
} as const;
